on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 12 * *" # At 03:30 on day-of-month 12

name: Open release PR

jobs:
  test:
    name: open-release-pr
    uses: kubewarden/github-actions/.github/workflows/reusable-release-pr.yml@f1695ca9a575bf58b85d6c3652c7ff7d1d12ec24 # v4.5.16
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
