on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 12 * *" # At 03:30 on day-of-month 12

name: Open release PR

jobs:
  test:
    name: open-release-pr
    uses: kubewarden/github-actions/.github/workflows/reusable-release-pr.yml@247608f0b5a1562a6fd2576e5b2e6cbe62551baf # v4.5.15
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
