on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      trigger_release:
        description: "Tag and trigger release manually"
        required: false
        default: true

name: Tag and Release on PR Merge

jobs:
  test:
    name: release-tag
    uses: kubewarden/github-actions/.github/workflows/reusable-release-tag.yml@605a03917fbc6b4b523145a1a78cf72a680f5f36 # v4.5.12
